version: 2

registries:
  npmjs:
    type: npm-registry
    url: https://registry.npmjs.org

  github-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NPM_AUTH_TOKEN }}
    replaces-base: false

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/"
    registries:
      - npmjs
      - github-packages
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "nav-frontend*"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
