allowBuilds:
  core-js: true
  esbuild: true
  msw: true
  protobufjs: true
  styled-components: true
minimumReleaseAge: 4320 # 3 days
ignoreScripts: true
savePrefix: ''
minimumReleaseAgeExclude:
  - minimatch@9.0.6
  - minimatch@9.0.7
  - protobufjs@8.0.2
  - ip-address@10.1.1
  - brace-expansion@5.0.6
  - ws@8.20.1
  - protobufjs@8.2.0
