apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomodiaperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: syfomodiaperson-session-key
  webproxy: true
  ingresses:
    - "https://syfomodiaperson.dev.intern.nav.no"
  env:
    - name: NAIS_CONTEXT
      value: 'dev'
    - name: NODE_ENV
      value: "production"
    - name: REDIS_HOST
      value: "syfomodiaperson-redis"
    - name: AUTH_REDIRECT_URI
      value: "https://syfomodiaperson.dev.intern.nav.no/oauth2/callback"
    - name: FASTLEGEREST_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.fastlegerest"
    - name: FASTLEGEREST_HOST
      value: "fastlegerest.intern.dev.nav.no"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "internarbeidsflatedecorator-q0.dev.intern.nav.no"
    - name: ISAKTIVITETSKRAV_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isaktivitetskrav"
    - name: ISAKTIVITETSKRAV_HOST
      value: "isaktivitetskrav.intern.dev.nav.no"
    - name: ISBEHANDLERDIALOG_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isbehandlerdialog"
    - name: ISBEHANDLERDIALOG_HOST
      value: "isbehandlerdialog.dev.intern.nav.no"
    - name: ISDIALOGMELDING_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isdialogmelding"
    - name: ISDIALOGMELDING_HOST
      value: "isdialogmelding.intern.dev.nav.no"
    - name: ISDIALOGMOTE_AAD_APP_CLIENT_ID
      value: "1705435b-f7e7-49d6-9fae-89375f28d68f"
    - name: ISDIALOGMOTE_HOST
      value: "isdialogmote.intern.dev.nav.no"
    - name: ISDIALOGMOTEKANDIDAT_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isdialogmotekandidat"
    - name: ISDIALOGMOTEKANDIDAT_HOST
      value: "isdialogmotekandidat.intern.dev.nav.no"
    - name: ISNARMESTELEDER_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isnarmesteleder"
    - name: ISNARMESTELEDER_HOST
      value: "isnarmesteleder.intern.dev.nav.no"
    - name: ISOPPFOLGINGSTILFELLE_HOST
      value: "isoppfolgingstilfelle.intern.dev.nav.no"
    - name: ISOPPFOLGINGSTILFELLE_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISPENGESTOPP_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.ispengestopp"
    - name: ISPENGESTOPP_HOST
      value: "ispengestopp.intern.dev.nav.no"
    - name: ISPERSONOPPGAVE_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.ispersonoppgave"
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: "dev-fss.personoversikt.modiacontextholder-q1"
    - name: ISPERSONOPPGAVE_HOST
      value: "ispersonoppgave.intern.dev.nav.no"
    - name: MODIACONTEXTHOLDER_HOST
      value: "modiacontextholder-q1.dev.intern.nav.no"
    - name: SYFOBEHANDLENDEENHET_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_HOST
      value: "syfobehandlendeenhet.intern.dev.nav.no"
    - name: EREG_HOST
      value: "ereg-services-q1.dev.intern.nav.no"
    - name: SYFOMOTEBEHOV_AAD_APP_CLIENT_ID
      value: "71e608a6-fad4-42f6-b8cf-0130c82fa78a"
    - name: SYFOMOTEBEHOV_HOST
      value: "syfomotebehov.dev.intern.nav.no"
    - name: SYFOOPPFOLGINGSPLANSERVICE_AAD_APP_CLIENT_ID
      value: "7d8c5d52-348f-48c2-b42f-f59cf6970fd3"
    - name: SYFOOPPFOLGINGSPLANSERVICE_HOST
      value: "syfooppfolgingsplanservice.dev.intern.nav.no"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoperson"
    - name: SYFOPERSON_HOST
      value: "syfoperson.intern.dev.nav.no"
    - name: SYFOSMREGISTER_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykmelding.syfosmregister"
    - name: SYFOSMREGISTER_HOST
      value: "smregister.dev.intern.nav.no"
    - name: SYKEPENGESOKNAD_BACKEND_AAD_APP_CLIENT_ID
      value: "dev-gcp.flex.sykepengesoknad-backend"
    - name: SYKEPENGESOKNAD_BACKEND_HOST
      value: "flex-intern-gateway.intern.dev.nav.no"
    - name: SYFOTILGANGSKONTROLL_AAD_APP_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_HOST
      value: "syfo-tilgangskontroll.dev.intern.nav.no"
    - name: SYFOVEILEDER_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoveileder"
    - name: SYFOVEILEDER_HOST
      value: "syfoveileder.intern.dev.nav.no"

