apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomodiaperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "unleash.nais.io"
        - host: "internarbeidsflatedecorator.prod-fss-pub.nais.io"
        - host: "modiacontextholder.prod-fss-pub.nais.io"
        - host: "ereg-services.prod-fss-pub.nais.io"
        - host: "syfomotebehov.prod-fss-pub.nais.io"
        - host: "syfooppfolgingsplanservice.prod-fss-pub.nais.io"
      rules:
        - application: fastlegerest
        - application: isaktivitetskrav
        - application: isbehandlerdialog
        - application: isdialogmelding
        - application: isdialogmote
        - application: isdialogmotekandidat
        - application: isnarmesteleder
        - application: isoppfolgingstilfelle
        - application: ispengestopp
        - application: ispersonoppgave
        - application: syfo-tilgangskontroll
        - application: syfobehandlendeenhet
        - application: syfoperson
        - application: syfoveileder
        - application: syfosmregister
          namespace: teamsykmelding
        - application: sykepengesoknad-backend
          namespace: flex
        - application: syfomodiaperson-redis
        - application: esyfovarsel
          namespace: team-esyfo
  envFrom:
    - secret: syfomodiaperson-session-key
    - secret: syfomodiaperson-redis-password
  ingresses:
    - "https://syfomodiaperson.intern.nav.no"
  env:
    - name: NAIS_CONTEXT
      value: 'prod'
    - name: NODE_ENV
      value: "production"
    - name: REDIS_HOST
      value: "syfomodiaperson-redis"
    - name: AUTH_REDIRECT_URI
      value: "https://syfomodiaperson.intern.nav.no/oauth2/callback"
    - name: EREG_HOST
      value: "https://ereg-services.prod-fss-pub.nais.io"
    - name: FASTLEGEREST_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.fastlegerest"
    - name: FASTLEGEREST_HOST
      value: "http://fastlegerest"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "https://internarbeidsflatedecorator.prod-fss-pub.nais.io"
    - name: ISAKTIVITETSKRAV_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isaktivitetskrav"
    - name: ISAKTIVITETSKRAV_HOST
      value: "http://isaktivitetskrav"
    - name: ISBEHANDLERDIALOG_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isbehandlerdialog"
    - name: ISBEHANDLERDIALOG_HOST
      value: "http://isbehandlerdialog"
    - name: ISDIALOGMELDING_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isdialogmelding"
    - name: ISDIALOGMELDING_HOST
      value: "http://isdialogmelding"
    - name: ISDIALOGMOTE_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isdialogmote"
    - name: ISDIALOGMOTE_HOST
      value: "http://isdialogmote"
    - name: ISDIALOGMOTEKANDIDAT_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isdialogmotekandidat"
    - name: ISDIALOGMOTEKANDIDAT_HOST
      value: "http://isdialogmotekandidat"
    - name: ISNARMESTELEDER_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isnarmesteleder"
    - name: ISNARMESTELEDER_HOST
      value: "http://isnarmesteleder"
    - name: ISOPPFOLGINGSTILFELLE_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISOPPFOLGINGSTILFELLE_HOST
      value: "http://isoppfolgingstilfelle"
    - name: ISPENGESTOPP_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.ispengestopp"
    - name: ISPENGESTOPP_HOST
      value: "http://ispengestopp"
    - name: ISPERSONOPPGAVE_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.ispersonoppgave"
    - name: ISPERSONOPPGAVE_HOST
      value: "http://ispersonoppgave"
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: "prod-fss.personoversikt.modiacontextholder"
    - name: MODIACONTEXTHOLDER_HOST
      value: "https://modiacontextholder.prod-fss-pub.nais.io"
    - name: SYFOBEHANDLENDEENHET_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_HOST
      value: "http://syfobehandlendeenhet"
    - name: SYFOMOTEBEHOV_AAD_APP_CLIENT_ID
      value: "prod-fss.team-esyfo.syfomotebehov"
    - name: SYFOMOTEBEHOV_HOST
      value: "https://syfomotebehov.prod-fss-pub.nais.io"
    - name: SYFOOPPFOLGINGSPLANSERVICE_AAD_APP_CLIENT_ID
      value: "prod-fss.team-esyfo.syfooppfolgingsplanservice"
    - name: SYFOOPPFOLGINGSPLANSERVICE_HOST
      value: "https://syfooppfolgingsplanservice.prod-fss-pub.nais.io"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfoperson"
    - name: SYFOPERSON_HOST
      value: "http://syfoperson"
    - name: SYFOSMREGISTER_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykmelding.syfosmregister"
    - name: SYFOSMREGISTER_HOST
      value: "http://syfosmregister.teamsykmelding"
    - name: SYKEPENGESOKNAD_BACKEND_AAD_APP_CLIENT_ID
      value: "prod-gcp.flex.sykepengesoknad-backend"
    - name: SYKEPENGESOKNAD_BACKEND_HOST
      value: "http://sykepengesoknad-backend.flex"
    - name: SYFOTILGANGSKONTROLL_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_HOST
      value: "http://syfo-tilgangskontroll"
    - name: SYFOVEILEDER_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfoveileder"
    - name: SYFOVEILEDER_HOST
      value: "http://syfoveileder"
    - name: ESYFOVARSEL_AAD_APP_CLIENT_ID
      value: "prod-gcp.team-esyfo.esyfovarsel"
    - name: ESYFOVARSEL_HOST
      value: "http://esyfovarsel.team-esyfo"
