apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomodiaperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "teamsykefravr-unleash-api.nav.cloud.nais.io"
        - host: "internarbeidsflatedecorator-q1.dev-fss-pub.nais.io"
        - host: "modiacontextholder-q1.dev-fss-pub.nais.io"
        - host: "ereg-services-q1.dev-fss-pub.nais.io"
        - host: "syfooppfolgingsplanservice.dev-fss-pub.nais.io"
        - host: "veilarboppfolging.dev-fss-pub.nais.io"
      rules:
        - application: fastlegerest
        - application: isaktivitetskrav
        - application: isarbeidsuforhet
        - application: isbehandlerdialog
        - application: isdialogmelding
        - application: isdialogmote
        - application: isdialogmotekandidat
        - application: ishuskelapp
        - application: isfrisktilarbeid
        - application: ismeroppfolging
        - application: isnarmesteleder
        - application: isoppfolgingstilfelle
        - application: ispengestopp
        - application: ispersonoppgave
        - application: istilgangskontroll
        - application: syfobehandlendeenhet
        - application: syfoperson
        - application: syfooversiktsrv
        - application: syfoveileder
        - application: syfosmregister
          namespace: teamsykmelding
        - application: sykepengesoknad-backend
          namespace: flex
        - application: flexjar-backend
          namespace: flex
        - application: syfomodiaperson-redis
        - application: esyfovarsel
          namespace: team-esyfo
        - application: syfomotebehov
          namespace: team-esyfo
        - application: lps-oppfolgingsplan-mottak
          namespace: team-esyfo
        - application: meroppfolging-backend
          namespace: team-esyfo
  envFrom:
    - secret: syfomodiaperson-session-key
    - secret: syfomodiaperson-redis-password
    - secret: syfomodiaperson-unleash-api-token
  ingresses:
    - "https://syfomodiaperson.intern.dev.nav.no"
  env:
    - name: NAIS_CONTEXT
      value: 'dev'
    - name: NODE_ENV
      value: "production"
    - name: REDIS_HOST
      value: "syfomodiaperson-redis"
    - name: AUTH_REDIRECT_URI
      value: "https://syfomodiaperson.intern.dev.nav.no/oauth2/callback"
    - name: FASTLEGEREST_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.fastlegerest"
    - name: FASTLEGEREST_HOST
      value: "http://fastlegerest"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "https://internarbeidsflatedecorator-q1.dev-fss-pub.nais.io"
    - name: ISAKTIVITETSKRAV_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isaktivitetskrav"
    - name: ISAKTIVITETSKRAV_HOST
      value: "http://isaktivitetskrav"
    - name: ISARBEIDSUFORHET_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isarbeidsuforhet"
    - name: ISARBEIDSUFORHET_HOST
      value: "http://isarbeidsuforhet"
    - name: ISBEHANDLERDIALOG_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isbehandlerdialog"
    - name: ISBEHANDLERDIALOG_HOST
      value: "http://isbehandlerdialog"
    - name: ISDIALOGMELDING_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isdialogmelding"
    - name: ISDIALOGMELDING_HOST
      value: "http://isdialogmelding"
    - name: ISDIALOGMOTE_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isdialogmote"
    - name: ISDIALOGMOTE_HOST
      value: "http://isdialogmote"
    - name: ISDIALOGMOTEKANDIDAT_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isdialogmotekandidat"
    - name: ISDIALOGMOTEKANDIDAT_HOST
      value: "http://isdialogmotekandidat"
    - name: ISFRISKTILARBEID_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isfrisktilarbeid"
    - name: ISFRISKTILARBEID_HOST
      value: "http://isfrisktilarbeid"
    - name: ISHUSKELAPP_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.ishuskelapp"
    - name: ISHUSKELAPP_HOST
      value: "http://ishuskelapp"
    - name: ISMEROPPFOLGING_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.ismeroppfolging"
    - name: ISMEROPPFOLGING_HOST
      value: "http://ismeroppfolging"
    - name: ISNARMESTELEDER_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isnarmesteleder"
    - name: ISNARMESTELEDER_HOST
      value: "http://isnarmesteleder"
    - name: ISOPPFOLGINGSTILFELLE_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISOPPFOLGINGSTILFELLE_HOST
      value: "http://isoppfolgingstilfelle"
    - name: ISPENGESTOPP_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.ispengestopp"
    - name: ISPENGESTOPP_HOST
      value: "http://ispengestopp"
    - name: ISPERSONOPPGAVE_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.ispersonoppgave"
    - name: ISPERSONOPPGAVE_HOST
      value: "http://ispersonoppgave"
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: "dev-fss.personoversikt.modiacontextholder-q1"
    - name: MODIACONTEXTHOLDER_HOST
      value: "https://modiacontextholder-q1.dev-fss-pub.nais.io"
    - name: SYFOBEHANDLENDEENHET_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_HOST
      value: "http://syfobehandlendeenhet"
    - name: EREG_HOST
      value: "https://ereg-services-q1.dev-fss-pub.nais.io"
    - name: SYFOMOTEBEHOV_AAD_APP_CLIENT_ID
      value: "dev-gcp.team-esyfo.syfomotebehov"
    - name: SYFOMOTEBEHOV_HOST
      value: "http://syfomotebehov.team-esyfo"
    - name: SYFOOPPFOLGINGSPLANSERVICE_AAD_APP_CLIENT_ID
      value: "dev-fss.team-esyfo.syfooppfolgingsplanservice"
    - name: SYFOOPPFOLGINGSPLANSERVICE_HOST
      value: "https://syfooppfolgingsplanservice.dev-fss-pub.nais.io"
    - name: LPS_OPPFOLGINGSPLAN_MOTTAK_AAD_APP_CLIENT_ID
      value: "dev-gcp.team-esyfo.lps-oppfolgingsplan-mottak"
    - name: LPS_OPPFOLGINGSPLAN_MOTTAK_HOST
      value: "http://lps-oppfolgingsplan-mottak.team-esyfo"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoperson"
    - name: SYFOPERSON_HOST
      value: "http://syfoperson"
    - name: SYFOOVERSIKTSRV_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfooversiktsrv"
    - name: SYFOOVERSIKTSRV_HOST
      value: "http://syfooversiktsrv"
    - name: SYFOSMREGISTER_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykmelding.syfosmregister"
    - name: SYFOSMREGISTER_HOST
      value: "http://syfosmregister.teamsykmelding"
    - name: SYKEPENGESOKNAD_BACKEND_AAD_APP_CLIENT_ID
      value: "dev-gcp.flex.sykepengesoknad-backend"
    - name: SYKEPENGESOKNAD_BACKEND_HOST
      value: "http://sykepengesoknad-backend.flex"
    - name: ISTILGANGSKONTROLL_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_HOST
      value: "http://istilgangskontroll"
    - name: SYFOVEILEDER_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoveileder"
    - name: SYFOVEILEDER_HOST
      value: "http://syfoveileder"
    - name: ESYFOVARSEL_AAD_APP_CLIENT_ID
      value: "dev-gcp.team-esyfo.esyfovarsel"
    - name: ESYFOVARSEL_HOST
      value: "http://esyfovarsel.team-esyfo"
    - name: FLEXJAR_AAD_APP_CLIENT_ID
      value: "dev-gcp.flex.flexjar-backend"
    - name: FLEXJAR_HOST
      value: "http://flexjar-backend.flex"
    - name: MEROPPFOLGING_BACKEND_AAD_APP_CLIENT_ID
      value: "dev-gcp.team-esyfo.meroppfolging-backend"
    - name: MEROPPFOLGING_BACKEND_HOST
      value: "http://meroppfolging-backend.team-esyfo"
    - name: VEILARBOPPFOLGING_AAD_APP_CLIENT_ID
      value: "dev-fss.pto.veilarboppfolging"
    - name: VEILARBOPPFOLGING_HOST
      value: "https://veilarboppfolging.dev-fss-pub.nais.io"
