name: Deploy unleash api-tokens
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/unleash-apitokens.yaml'
      - '.nais/unleash/unleash-apitoken-dev.yaml'
      - '.nais/unleash/unleash-apitoken-prod.yaml'
jobs:
  apply-apitoken-unleash:
    name: Apply ApiToken for Unleash to cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash/unleash-apitoken-dev.yaml
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/unleash/unleash-apitoken-prod.yaml
